//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperGridPaging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channels
    {
        public int ID { get; set; }
        public string matricola { get; set; }
        public string disegno { get; set; }
        public string descrizione { get; set; }
        public string nodeid { get; set; }
        public string result { get; set; }
        public float coppia { get; set; }
        public float angolo { get; set; }
        public int prgnr { get; set; }
        public string prgname { get; set; }
        public System.DateTime date { get; set; }
        public string NomeFile { get; set; }
        public string lastcmd { get; set; }
        public string laststeprow { get; set; }
        public string laststepcolumn { get; set; }
        public string qualitycode { get; set; }
        public int rootobj_ID { get; set; }
    
        public  Rootobjects Rootobjects { get; set; }
    }
}
